[package]
name        = "write_flux"
version     = "0.1.10"
keywords    = ["write_flux", "influxdb", "influxdb2", "reqwest"]
description = "Influxdb2 point client"
edition     = "2024"
license     = "MIT OR Apache-2.0"
authors     = [ "B3K7" ]

[dependencies]
chrono              = "0.4"
clap                = { version = "4.1", features = ["derive"] }
clap-verbosity-flag = "2.0"
env_logger          = "0.10.0"
log                 = "0.4"
reqwest             = { version = "0.11", features = ["rustls-tls"] }
serde               = { version = "1.0", features = ["derive"] }
serde_json          = "1.0"
tokio               = { version = "1.25", features = ["full"] }

[profile.release]
strip = "symbols"
opt-level = "z"
lto = "fat"
codegen-units = 1
target-cpu = "native"
panic = "abort"

